import type { ThemePreset } from './types';

export const themes: ThemePreset[] = [
  { name: "Coral",    theme: { accentColor: "#f75c30", panelColor: "#ffffff", messageColor: "#161425", messageTextColor: "#ffffff", userBubbleColor: "#ffffff", userTextColor: "#0d1221", launcherColor: "#f75c30",  surfaceStyle: "matte",  cornerRadius: 18 } },
  { name: "Forest",   theme: { accentColor: "#0f6b54", panelColor: "#ffffff", messageColor: "#073b33", messageTextColor: "#ffffff", userBubbleColor: "#f7fffb", userTextColor: "#0d241e", launcherColor: "#0f6b54",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Violet",   theme: { accentColor: "#5b5cff", panelColor: "#ffffff", messageColor: "#19173a", messageTextColor: "#ffffff", userBubbleColor: "#fbfbff", userTextColor: "#17152d", launcherColor: "#5b5cff",  surfaceStyle: "glass",  cornerRadius: 18 } },
  { name: "Graphite", theme: { accentColor: "#222736", panelColor: "#ffffff", messageColor: "#111827", messageTextColor: "#ffffff", userBubbleColor: "#ffffff", userTextColor: "#111827", launcherColor: "#222736",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Gold",     theme: { accentColor: "#c88910", panelColor: "#fffefa", messageColor: "#2a1b06", messageTextColor: "#fff8e5", userBubbleColor: "#ffffff", userTextColor: "#20160a", launcherColor: "#c88910",  surfaceStyle: "matte",  cornerRadius: 18 } },
  { name: "Teal",     theme: { accentColor: "#00796b", panelColor: "#ffffff", messageColor: "#073b36", messageTextColor: "#ffffff", userBubbleColor: "#f6fffd", userTextColor: "#06231f", launcherColor: "#00796b",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Ink",      theme: { accentColor: "#121826", panelColor: "#f9fafb", messageColor: "#0b1020", messageTextColor: "#ffffff", userBubbleColor: "#ffffff", userTextColor: "#111827", launcherColor: "#121826",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Cloud",    theme: { accentColor: "#64748b", panelColor: "#ffffff", messageColor: "#334155", messageTextColor: "#ffffff", userBubbleColor: "#f8fafc", userTextColor: "#0f172a", launcherColor: "#64748b",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Ember",    theme: { accentColor: "#d9480f", panelColor: "#fffaf7", messageColor: "#321007", messageTextColor: "#fff6ed", userBubbleColor: "#ffffff", userTextColor: "#25120a", launcherColor: "#d9480f",  surfaceStyle: "matte",  cornerRadius: 18 } },
  { name: "Ocean",    theme: { accentColor: "#0b69a3", panelColor: "#ffffff", messageColor: "#082f49", messageTextColor: "#ffffff", userBubbleColor: "#f5fbff", userTextColor: "#0c2638", launcherColor: "#0b69a3",  surfaceStyle: "glass",  cornerRadius: 18 } },
  { name: "Mint",     theme: { accentColor: "#13a37f", panelColor: "#ffffff", messageColor: "#064e3b", messageTextColor: "#ffffff", userBubbleColor: "#f5fffb", userTextColor: "#073b33", launcherColor: "#13a37f",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Rose",     theme: { accentColor: "#db2777", panelColor: "#fffafd", messageColor: "#4a102a", messageTextColor: "#ffffff", userBubbleColor: "#ffffff", userTextColor: "#381525", launcherColor: "#db2777",  surfaceStyle: "matte",  cornerRadius: 18 } },
  { name: "Indigo",   theme: { accentColor: "#4338ca", panelColor: "#ffffff", messageColor: "#1e1b4b", messageTextColor: "#ffffff", userBubbleColor: "#fafaff", userTextColor: "#191633", launcherColor: "#4338ca",  surfaceStyle: "glass",  cornerRadius: 18 } },
  { name: "Slate",    theme: { accentColor: "#475569", panelColor: "#ffffff", messageColor: "#1f2937", messageTextColor: "#ffffff", userBubbleColor: "#f9fafb", userTextColor: "#111827", launcherColor: "#475569",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Lime",     theme: { accentColor: "#4d7c0f", panelColor: "#fffffb", messageColor: "#1f2a0a", messageTextColor: "#faffef", userBubbleColor: "#ffffff", userTextColor: "#1a2309", launcherColor: "#4d7c0f",  surfaceStyle: "matte",  cornerRadius: 18 } },
  { name: "Ruby",     theme: { accentColor: "#b91c1c", panelColor: "#fffafa", messageColor: "#3f0d0d", messageTextColor: "#ffffff", userBubbleColor: "#ffffff", userTextColor: "#2d1111", launcherColor: "#b91c1c",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Sand",     theme: { accentColor: "#9a6b28", panelColor: "#fffdf8", messageColor: "#2f2417", messageTextColor: "#fff8ea", userBubbleColor: "#ffffff", userTextColor: "#2b2117", launcherColor: "#9a6b28",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Sky",      theme: { accentColor: "#0284c7", panelColor: "#ffffff", messageColor: "#083344", messageTextColor: "#ffffff", userBubbleColor: "#f7fcff", userTextColor: "#082f49", launcherColor: "#0284c7",  surfaceStyle: "glass",  cornerRadius: 18 } },
  { name: "Plum",     theme: { accentColor: "#7e22ce", panelColor: "#fffaff", messageColor: "#32104f", messageTextColor: "#ffffff", userBubbleColor: "#ffffff", userTextColor: "#261139", launcherColor: "#7e22ce",  surfaceStyle: "matte",  cornerRadius: 18 } },
  { name: "Cypress",  theme: { accentColor: "#155e4b", panelColor: "#fbfffd", messageColor: "#092f28", messageTextColor: "#ffffff", userBubbleColor: "#ffffff", userTextColor: "#09231e", launcherColor: "#155e4b",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Carbon",   theme: { accentColor: "#18181b", panelColor: "#fbfbfc", messageColor: "#18181b", messageTextColor: "#ffffff", userBubbleColor: "#ffffff", userTextColor: "#18181b", launcherColor: "#18181b",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Cream",    theme: { accentColor: "#b45309", panelColor: "#fffaf0", messageColor: "#2b1707", messageTextColor: "#fff7e4", userBubbleColor: "#fffdf7", userTextColor: "#27180a", launcherColor: "#b45309",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Azure",    theme: { accentColor: "#2563eb", panelColor: "#ffffff", messageColor: "#172554", messageTextColor: "#ffffff", userBubbleColor: "#f8fbff", userTextColor: "#172554", launcherColor: "#2563eb",  surfaceStyle: "glass",  cornerRadius: 18 } },
  { name: "Clay",     theme: { accentColor: "#a4492f", panelColor: "#fffaf7", messageColor: "#3b1d14", messageTextColor: "#fff6ef", userBubbleColor: "#ffffff", userTextColor: "#2d1912", launcherColor: "#a4492f",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Neon",     theme: { accentColor: "#16a34a", panelColor: "#fbfffd", messageColor: "#052e16", messageTextColor: "#dcfce7", userBubbleColor: "#ffffff", userTextColor: "#052e16", launcherColor: "#16a34a",  surfaceStyle: "glass",  cornerRadius: 18 } },
  { name: "Mono",     theme: { accentColor: "#3f3f46", panelColor: "#ffffff", messageColor: "#27272a", messageTextColor: "#ffffff", userBubbleColor: "#fafafa", userTextColor: "#18181b", launcherColor: "#3f3f46",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Peach",    theme: { accentColor: "#ea580c", panelColor: "#fffaf7", messageColor: "#431407", messageTextColor: "#ffffff", userBubbleColor: "#ffffff", userTextColor: "#2b1509", launcherColor: "#ea580c",  surfaceStyle: "matte",  cornerRadius: 18 } },
  { name: "Alpine",   theme: { accentColor: "#0369a1", panelColor: "#fbfdff", messageColor: "#0c4a6e", messageTextColor: "#ffffff", userBubbleColor: "#ffffff", userTextColor: "#082f49", launcherColor: "#0369a1",  surfaceStyle: "solid",  cornerRadius: 18 } },
  { name: "Berry",    theme: { accentColor: "#be185d", panelColor: "#fffafe", messageColor: "#4c0519", messageTextColor: "#ffffff", userBubbleColor: "#ffffff", userTextColor: "#3b1020", launcherColor: "#be185d",  surfaceStyle: "matte",  cornerRadius: 18 } },
  { name: "Midnight", theme: { accentColor: "#312e81", panelColor: "#ffffff", messageColor: "#11113f", messageTextColor: "#ffffff", userBubbleColor: "#f8f8ff", userTextColor: "#16163a", launcherColor: "#312e81",  surfaceStyle: "solid",  cornerRadius: 18 } },
];

export function getTheme(name: string): ThemePreset | undefined {
  return themes.find((t) => t.name.toLowerCase() === name.toLowerCase());
}
