"use client";

import Link from "next/link";
import { useState, useSyncExternalStore } from "react";
import styles from "./publish-page.module.css";
import stepStyles from "./widget-designer.module.css";

// ── Types ─────────────────────────────────────────────────────────────────────

type TierKey = "guest" | "loggedIn" | "pro";
type TierItemRef = { id: string; name: string };
type TierConfig = { model: TierItemRef | null; rateLimitPolicy: TierItemRef | null; guardrails: TierItemRef[]; mcpTools: TierItemRef[] };
type SavedTierConfig = {
  tiers: Record<TierKey, TierConfig>;
  gatewayUrl?: string;
  controlPlaneUrl?: string;
  savedAt?: string;
} | null;

interface WidgetConfig {
  assistantName: string;
  launcherLabel: string;
  greeting: string;
  subGreeting: string;
  panelSize: string;
  animation: string;
  shadow: string;
  accentColor: string;
  panelColor: string;
  messageColor: string;
  messageTextColor: string;
  userBubbleColor: string;
  userTextColor: string;
  launcherColor: string;
  stageBackground: string;
  surfaceStyle: string;
  cornerRadius: number;
}

// ── Defaults ──────────────────────────────────────────────────────────────────

const DEFAULT: WidgetConfig = {
  assistantName: "Acme Support Copilot",
  launcherLabel: "AI",
  greeting: "Need help choosing a plan?",
  subGreeting: "I can answer product questions, compare pricing, and create a support ticket.",
  panelSize: "standard",
  animation: "slide",
  shadow: "deep",
  accentColor: "#f75c30",
  panelColor: "#ffffff",
  messageColor: "#161425",
  messageTextColor: "#ffffff",
  userBubbleColor: "#ffffff",
  userTextColor: "#0d1221",
  launcherColor: "#f75c30",
  stageBackground: "#fcfbfa",
  surfaceStyle: "matte",
  cornerRadius: 18,
};

const EMPTY_STORAGE_SNAPSHOT = "";

function subscribeToSessionStorage(onStoreChange: () => void) {
  if (typeof window === "undefined") return () => {};

  const timer = window.setTimeout(onStoreChange, 0);
  const handleStorage = (event: StorageEvent) => {
    if (
      event.storageArea === window.sessionStorage &&
      (event.key === "chatdock_widget_config" || event.key === "chatdock_tier_config")
    ) {
      onStoreChange();
    }
  };

  window.addEventListener("storage", handleStorage);

  return () => {
    window.clearTimeout(timer);
    window.removeEventListener("storage", handleStorage);
  };
}

function emptyStorageSnapshot() {
  return EMPTY_STORAGE_SNAPSHOT;
}

function getWidgetConfigSnapshot() {
  if (typeof window === "undefined") return EMPTY_STORAGE_SNAPSHOT;
  return window.sessionStorage.getItem("chatdock_widget_config") ?? EMPTY_STORAGE_SNAPSHOT;
}

function getTierConfigSnapshot() {
  if (typeof window === "undefined") return EMPTY_STORAGE_SNAPSHOT;
  return window.sessionStorage.getItem("chatdock_tier_config") ?? EMPTY_STORAGE_SNAPSHOT;
}

function readConfig(raw: string): WidgetConfig {
  try {
    if (raw) return { ...DEFAULT, ...JSON.parse(raw) };
  } catch { /* ignore */ }
  return DEFAULT;
}

function readTierConfig(raw: string): SavedTierConfig {
  try {
    if (raw) return JSON.parse(raw);
  } catch { /* ignore */ }
  return null;
}

function q(s: string) { return JSON.stringify(s); }
function qn(n: number) { return String(n); }

// ── Code generators ───────────────────────────────────────────────────────────

function buildWidgetComponent(cfg: WidgetConfig, tierCfg: SavedTierConfig): string {
  const guestModel   = tierCfg?.tiers.guest.model?.name    ?? "gpt-4o-mini";
  const loggedModel  = tierCfg?.tiers.loggedIn.model?.name ?? "gpt-4o";
  const proModel     = tierCfg?.tiers.pro.model?.name      ?? "claude-3-5-sonnet";

  return `// ChatDockWidget.tsx
// Generated by ChatDock — paste this file anywhere in your React / Next.js project.
// No extra packages needed — only React.
// Pair it with app/api/chat/route.ts (see the backend proxy file below).

"use client";

import { useEffect, useRef, useState } from "react";

// ── Configuration ─────────────────────────────────────────────────────────────
// Edit these values to customise your chatbot.

const WIDGET_CONFIG = {
  assistantName: ${q(cfg.assistantName)},
  launcherLabel: ${q(cfg.launcherLabel)},
  greeting:      ${q(cfg.greeting)},
  subGreeting:   ${q(cfg.subGreeting)},
  accentColor:   ${q(cfg.accentColor)},
  panelColor:    ${q(cfg.panelColor)},
  messageColor:  ${q(cfg.messageColor)},
  messageTextColor: ${q(cfg.messageTextColor)},
  userBubbleColor: ${q(cfg.userBubbleColor)},
  userTextColor: ${q(cfg.userTextColor)},
  launcherColor: ${q(cfg.launcherColor)},
  surfaceStyle:  ${q(cfg.surfaceStyle)} as "solid" | "matte" | "glass",
  animation:     ${q(cfg.animation)} as "slide" | "pop" | "fade" | "spring" | "drawer" | "flip" | "zoom",
  shadow:        ${q(cfg.shadow)} as "soft" | "deep" | "flat",
  panelSize:     ${q(cfg.panelSize)} as "compact" | "standard" | "wide",
  cornerRadius:  ${qn(cfg.cornerRadius)},
  // Your backend chat endpoint — see app/api/chat/route.ts
  apiEndpoint:   "/api/chat",
} as const;

const TIER_MODELS = {
  guest:    ${q(guestModel)},
  loggedIn: ${q(loggedModel)},
  pro:      ${q(proModel)},
} as const;

// ── Styles (injected once into <head> — no CSS files needed) ──────────────────

const WIDGET_CSS = \`
.cd-root {
  position: fixed;
  bottom: 22px;
  right: 22px;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 10px;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  z-index: 9999;
}
.cd-panel {
  width: 340px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  transition: transform 240ms cubic-bezier(0.34,1.56,0.64,1), opacity 200ms ease;
}
.cd-panel--closed { pointer-events: none; opacity: 0; }
.cd-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 14px;
  color: #fff;
  flex-shrink: 0;
  height: 48px;
}
.cd-header-left { display: flex; align-items: center; gap: 8px; }
.cd-header-left strong { font-size: 14px; font-weight: 700; }
.cd-online { width: 8px; height: 8px; border-radius: 50%; background: rgba(255,255,255,0.45); }
.cd-close {
  background: none; border: none; color: rgba(255,255,255,0.75);
  font-size: 14px; cursor: pointer; padding: 3px 7px; border-radius: 5px;
  line-height: 1; font-family: inherit;
}
.cd-close:hover { background: rgba(255,255,255,0.15); }
.cd-messages {
  overflow-y: auto; padding: 12px;
  display: flex; flex-direction: column; gap: 9px;
}
.cd-messages::-webkit-scrollbar { width: 4px; }
.cd-messages::-webkit-scrollbar-thumb { border-radius: 999px; background: rgba(0,0,0,0.12); }
.cd-bubble {
  padding: 10px 13px; font-size: 13px; line-height: 1.55;
  max-width: 87%; word-break: break-word;
}
.cd-greeting-title { font-weight: 700; font-size: 13px; }
.cd-greeting-sub   { margin-top: 4px; font-size: 12px; opacity: 0.82; }
.cd-typing { display: flex; gap: 5px; align-items: center; padding: 12px 14px; }
.cd-dot {
  display: inline-block; width: 6px; height: 6px; border-radius: 50%;
  animation: cdBounce 1.2s infinite ease-in-out;
}
@keyframes cdBounce {
  0%,80%,100% { transform: translateY(0); opacity: 0.4; }
  40%          { transform: translateY(-5px); opacity: 1; }
}
.cd-input-row {
  display: flex; align-items: center; gap: 7px; padding: 10px 12px;
  flex-shrink: 0; border-top: 1px solid rgba(0,0,0,0.07); height: 54px;
}
.cd-text {
  flex: 1; border: 1px solid rgba(13,18,33,0.12); padding: 7px 11px;
  font-size: 13px; color: #0d1221; background: #fff; font-family: inherit;
  outline: none; min-width: 0;
}
.cd-text:focus { border-color: rgba(13,18,33,0.3); }
.cd-send {
  width: 32px; height: 32px; border: none; color: #fff; font-size: 16px;
  cursor: pointer; display: grid; place-items: center; flex-shrink: 0;
  border-radius: 50%; font-family: inherit;
}
.cd-send:disabled { opacity: 0.45; cursor: wait; }
.cd-launcher {
  width: 50px; height: 50px; border-radius: 50%; border: none; color: #fff;
  font-size: 15px; font-weight: 800; cursor: pointer; display: grid;
  place-items: center; flex-shrink: 0; font-family: inherit;
  transition: transform 150ms;
}
.cd-launcher:hover { transform: scale(1.07); }
\`;

// ── Animation transform ───────────────────────────────────────────────────────

function closedTransform(anim: typeof WIDGET_CONFIG.animation): string {
  switch (anim) {
    case "pop":    return "scale(0.7) translateY(20px)";
    case "fade":   return "translateY(0) scale(1)";
    case "zoom":   return "scale(0.5)";
    case "flip":   return "perspective(600px) rotateX(18deg)";
    case "drawer": return "translateX(110%)";
    case "spring": return "translateY(28px)";
    default:       return "translateY(22px)";
  }
}

const PANEL_H = { compact: 480, standard: 560, wide: 600 } as const;
const SHADOWS = {
  soft: "0 4px 20px rgba(0,0,0,0.10)",
  deep: "0 12px 48px rgba(0,0,0,0.22)",
  flat: "none",
} as const;

// ── Widget component ──────────────────────────────────────────────────────────

export function ChatDockWidget({
  userTier = "guest",
}: {
  userTier?: "guest" | "loggedIn" | "pro";
}) {
  const [open, setOpen]         = useState(false);
  const [msgs, setMsgs]         = useState<Array<{ role: "user" | "assistant"; text: string; id: number }>>([]);
  const [input, setInput]       = useState("");
  const [sending, setSending]   = useState(false);
  const [streaming, setStreaming] = useState("");
  const bottomRef = useRef<HTMLDivElement>(null);
  const abortRef  = useRef<AbortController | null>(null);

  const cfg = WIDGET_CONFIG;
  const r  = cfg.cornerRadius;
  const ph = PANEL_H[cfg.panelSize];
  const panelBg =
    cfg.surfaceStyle === "glass" ? cfg.panelColor + "cc" :
    cfg.surfaceStyle === "matte" ? cfg.panelColor + "fa" : cfg.panelColor;

  useEffect(() => {
    if (!document.getElementById("chatdock-css")) {
      const el = document.createElement("style");
      el.id = "chatdock-css";
      el.textContent = WIDGET_CSS;
      document.head.appendChild(el);
    }
    return () => { abortRef.current?.abort(); };
  }, []);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [msgs, streaming]);

  async function send() {
    const text = input.trim();
    if (!text || sending) return;

    const userMsg = { role: "user" as const, text, id: Date.now() };
    const history = [...msgs, userMsg];
    setMsgs(history);
    setInput("");
    setSending(true);
    setStreaming("");

    const ctrl = new AbortController();
    abortRef.current = ctrl;

    try {
      const res = await fetch(cfg.apiEndpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        signal: ctrl.signal,
        body: JSON.stringify({
          messages: history.map((m) => ({ role: m.role, content: m.text })),
          model: TIER_MODELS[userTier],
          userTier,
        }),
      });

      if (!res.ok || !res.body) throw new Error(\`API error \${res.status}\`);

      const reader = res.body.getReader();
      const dec    = new TextDecoder();
      let buf = "";
      let ev  = "";
      let acc = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buf += dec.decode(value, { stream: true });
        const lines = buf.split("\\n");
        buf = lines.pop() ?? "";

        for (const line of lines) {
          if (line.startsWith("event: ")) { ev = line.slice(7).trim(); continue; }
          if (!line.startsWith("data: "))  continue;
          try {
            const d = JSON.parse(line.slice(6));
            if (ev === "delta") {
              acc += (d.content as string) ?? "";
              setStreaming(acc);
            } else if (ev === "done") {
              setMsgs((m) => [...m, { role: "assistant", text: acc, id: Date.now() }]);
              setStreaming("");
            } else if (ev === "error") {
              setMsgs((m) => [...m, { role: "assistant", text: \`Error: \${d.message}\`, id: Date.now() }]);
            }
          } catch { /* skip malformed */ }
          ev = "";
        }
      }
    } catch (e) {
      if (e instanceof Error && e.name === "AbortError") return;
      setMsgs((m) => [...m, {
        role: "assistant",
        text: "Connection failed. Please check your setup and try again.",
        id: Date.now(),
      }]);
    } finally {
      setSending(false);
      setStreaming("");
    }
  }

  return (
    <div className="cd-root">
      <div
        className={\`cd-panel\${open ? "" : " cd-panel--closed"}\`}
        style={{
          height: ph,
          borderRadius: r,
          background: panelBg,
          boxShadow: SHADOWS[cfg.shadow],
          transform: open ? "translateY(0) scale(1)" : closedTransform(cfg.animation),
          ...(cfg.surfaceStyle === "glass" ? { backdropFilter: "blur(20px)" } : {}),
        }}
      >
        {/* Header */}
        <div className="cd-header" style={{ background: cfg.accentColor, borderRadius: \`\${r}px \${r}px 0 0\` }}>
          <div className="cd-header-left">
            <span className="cd-online" />
            <strong>{cfg.assistantName}</strong>
          </div>
          <button className="cd-close" onClick={() => setOpen(false)}>✕</button>
        </div>

        {/* Messages */}
        <div className="cd-messages" style={{ height: ph - 48 - 54 }}>
          <div
            className="cd-bubble"
            style={{ background: cfg.messageColor, color: cfg.messageTextColor, borderRadius: \`4px \${r * 0.65}px \${r * 0.65}px\`, alignSelf: "flex-start" }}
          >
            <div className="cd-greeting-title">{cfg.greeting}</div>
            {cfg.subGreeting && <div className="cd-greeting-sub">{cfg.subGreeting}</div>}
          </div>

          {msgs.map((m) => (
            <div
              key={m.id}
              className="cd-bubble"
              style={m.role === "user"
                ? { background: cfg.userBubbleColor, color: cfg.userTextColor, border: "1px solid rgba(0,0,0,0.07)", borderRadius: \`\${r * 0.65}px \${r * 0.65}px 4px\`, alignSelf: "flex-end" }
                : { background: cfg.messageColor, color: cfg.messageTextColor, borderRadius: \`4px \${r * 0.65}px \${r * 0.65}px\`, alignSelf: "flex-start" }
              }
            >
              {m.text}
            </div>
          ))}

          {sending && streaming && (
            <div className="cd-bubble" style={{ background: cfg.messageColor, color: cfg.messageTextColor, borderRadius: \`4px \${r * 0.65}px \${r * 0.65}px\`, alignSelf: "flex-start" }}>
              {streaming}
            </div>
          )}

          {sending && !streaming && (
            <div className="cd-typing" style={{ background: cfg.messageColor, borderRadius: \`4px \${r * 0.65}px \${r * 0.65}px\`, alignSelf: "flex-start" }}>
              {[0, 1, 2].map((i) => (
                <span key={i} className="cd-dot" style={{ background: cfg.messageTextColor, animationDelay: \`\${i * 0.18}s\` }} />
              ))}
            </div>
          )}
          <div ref={bottomRef} />
        </div>

        {/* Input */}
        <div className="cd-input-row">
          <input
            className="cd-text"
            style={{ borderRadius: r * 0.45 }}
            placeholder="Type a message…"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) send(); }}
            disabled={sending}
          />
          <button className="cd-send" style={{ background: cfg.accentColor }} onClick={send} disabled={sending}>
            ↑
          </button>
        </div>
      </div>

      {/* Launcher */}
      <button
        className="cd-launcher"
        style={{ background: cfg.launcherColor, boxShadow: SHADOWS[cfg.shadow] }}
        onClick={() => setOpen((o) => !o)}
      >
        {open ? "✕" : cfg.launcherLabel}
      </button>
    </div>
  );
}
`;
}

function buildApiRoute(cfg: WidgetConfig, tierCfg: SavedTierConfig): string {
  const gwUrl = tierCfg?.gatewayUrl ?? "https://your-org.truefoundry.cloud/api/llm";
  const guestModel   = tierCfg?.tiers.guest.model?.name    ?? "gpt-4o-mini";
  const loggedModel  = tierCfg?.tiers.loggedIn.model?.name ?? "gpt-4o";
  const proModel     = tierCfg?.tiers.pro.model?.name      ?? "claude-3-5-sonnet";
  const botName = cfg.assistantName;

  return `// app/api/chat/route.ts
// Backend proxy for ChatDockWidget — keeps your TrueFoundry API key server-side.
// Add TFY_API_KEY to your .env.local file.

import OpenAI from "openai";

const client = new OpenAI({
  baseURL: ${q(gwUrl)},
  apiKey:  process.env.TFY_API_KEY ?? "",
});

const TIER_MODELS: Record<string, string> = {
  guest:    ${q(guestModel)},
  loggedIn: ${q(loggedModel)},
  pro:      ${q(proModel)},
};

const SYSTEM_PROMPT = \`You are ${botName}, a helpful AI assistant. Be concise, friendly, and accurate.\`;

export async function POST(req: Request) {
  const { messages, model, userTier = "guest" } = await req.json() as {
    messages: Array<{ role: string; content: string }>;
    model?: string;
    userTier?: string;
  };

  if (!messages?.length) {
    return Response.json({ error: "messages required" }, { status: 400 });
  }

  const resolvedModel = model ?? TIER_MODELS[userTier] ?? TIER_MODELS.guest;

  const stream = await client.chat.completions.create({
    model: resolvedModel,
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      ...messages,
    ],
    stream: true,
  });

  // Stream SSE back to the widget
  const encoder = new TextEncoder();
  const readable = new ReadableStream({
    async start(controller) {
      function send(event: string, data: unknown) {
        controller.enqueue(encoder.encode(\`event: \${event}\\ndata: \${JSON.stringify(data)}\\n\\n\`));
      }

      try {
        for await (const chunk of stream) {
          const delta = chunk.choices[0]?.delta?.content;
          if (delta) send("delta", { content: delta });
        }
        send("done", { model: resolvedModel });
      } catch (err) {
        send("error", { message: err instanceof Error ? err.message : "Stream error" });
      } finally {
        controller.close();
      }
    },
  });

  return new Response(readable, {
    headers: {
      "Content-Type":  "text/event-stream",
      "Cache-Control": "no-cache",
      "Connection":    "keep-alive",
    },
  });
}
`;
}

function buildUsageSnippet(hasTiers: boolean): string {
  return [
    `// app/layout.tsx  (or any page you want the widget on)`,
    `import { ChatDockWidget } from "@/components/ChatDockWidget";`,
    ``,
    `export default function RootLayout({ children }: { children: React.ReactNode }) {`,
    `  // Replace with your real auth logic to get the user's tier`,
    `  const userTier = getUserTier(); // "guest" | "loggedIn" | "pro"`,
    ``,
    `  return (`,
    `    <html lang="en">`,
    `      <body>`,
    `        {children}`,
    `        <ChatDockWidget${hasTiers ? ' userTier={userTier}' : ""} />`,
    `      </body>`,
    `    </html>`,
    `  );`,
    `}`,
  ].join("\n");
}

function buildEnvSnippet(tierCfg: SavedTierConfig): string {
  const gwUrl = tierCfg?.gatewayUrl ?? "https://your-org.truefoundry.cloud/api/llm";
  return [
    `# .env.local`,
    `# Your TrueFoundry Personal Access Token (PAT) — never expose this on the client`,
    `TFY_API_KEY=tfy-...`,
    ``,
    `# Gateway base URL (already in your ChatDockWidget.tsx config, but useful for reference)`,
    `# ${gwUrl}`,
  ].join("\n");
}

function buildClaudePrompt(cfg: WidgetConfig, tierCfg: SavedTierConfig, widgetCode: string, apiRouteCode: string, usageCode: string, envCode: string): string {
  const gwUrl = tierCfg?.gatewayUrl ?? "https://your-org.truefoundry.cloud/api/llm";
  const hasTiers = tierCfg !== null;
  return [
    `<task>`,
    `Add a production chat widget to my Next.js project.`,
    `I configured it in ChatDock and need you to create the files below exactly as written.`,
    `</task>`,
    ``,
    `<context>`,
    `- Framework: Next.js 14+ (App Router)`,
    `- Widget name: ${cfg.assistantName}`,
    `- Gateway: TrueFoundry AI Gateway at ${gwUrl}`,
    `- The widget has three user tiers: guest, loggedIn, pro — each gets a different model`,
    `- All styles are self-contained (injected via <style> tag — no extra CSS files)`,
    `- The widget uses Server-Sent Events for streaming responses`,
    `</context>`,
    ``,
    `<files>`,
    ``,
    `<file path="components/ChatDockWidget.tsx">`,
    widgetCode,
    `</file>`,
    ``,
    `<file path="app/api/chat/route.ts">`,
    apiRouteCode,
    `</file>`,
    ``,
    `<file path=".env.local" action="append">`,
    envCode,
    `</file>`,
    ``,
    `</files>`,
    ``,
    `<instructions>`,
    `1. Create \`components/ChatDockWidget.tsx\` with the exact code above — do not modify it.`,
    `2. Create \`app/api/chat/route.ts\` with the exact code above.`,
    `3. Add \`TFY_API_KEY=tfy-...\` to \`.env.local\` (fill in your real key).`,
    hasTiers ? `4. Import ChatDockWidget and add <ChatDockWidget userTier={userTier} /> to your layout.tsx.` : `4. Import ChatDockWidget and add <ChatDockWidget /> to your layout.tsx.`,
    `5. Install the openai package if not already installed: npm install openai`,
    `6. Run npm run dev to test.`,
    `</instructions>`,
    ``,
    `<usage_example>`,
    usageCode,
    `</usage_example>`,
  ].join("\n");
}

function buildCodexPrompt(cfg: WidgetConfig, tierCfg: SavedTierConfig, widgetCode: string, apiRouteCode: string, usageCode: string, envCode: string): string {
  const gwUrl = tierCfg?.gatewayUrl ?? "https://your-org.truefoundry.cloud/api/llm";
  return [
    `# Add ChatDock Widget to My Next.js App`,
    ``,
    `## Goal`,
    `Create a self-contained AI chat widget and backend proxy for my Next.js 14 project.`,
    `The widget was configured in ChatDock (TrueFoundry AI Gateway at ${gwUrl}).`,
    ``,
    `## Widget spec`,
    `- Name: ${cfg.assistantName}`,
    `- Accent: ${cfg.accentColor}  Panel: ${cfg.panelColor}`,
    `- Animation: ${cfg.animation}  Shadow: ${cfg.shadow}  Size: ${cfg.panelSize}`,
    `- Corner radius: ${cfg.cornerRadius}px  Surface: ${cfg.surfaceStyle}`,
    ``,
    `## Files to create`,
    ``,
    `### components/ChatDockWidget.tsx`,
    `\`\`\`tsx`,
    widgetCode,
    `\`\`\``,
    ``,
    `### app/api/chat/route.ts`,
    `\`\`\`ts`,
    apiRouteCode,
    `\`\`\``,
    ``,
    `### .env.local (append)`,
    `\`\`\``,
    envCode,
    `\`\`\``,
    ``,
    `## How to use in layout.tsx`,
    `\`\`\`tsx`,
    usageCode,
    `\`\`\``,
    ``,
    `## Steps`,
    `1. Create the two files above exactly as written`,
    `2. Append the env vars to .env.local and set TFY_API_KEY`,
    `3. npm install openai (if not already installed)`,
    `4. Add <ChatDockWidget /> to app/layout.tsx inside <body>`,
    `5. Run npm run dev and open the app — click the launcher button to test`,
  ].join("\n");
}

// ── Copy button ───────────────────────────────────────────────────────────────

function CopyButton({ text, label = "Copy" }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false);
  function copy() {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }
  return (
    <button className={`${styles.copyBtn} ${copied ? styles.copyBtnDone : ""}`} onClick={copy}>
      {copied ? "✓ Copied" : label}
    </button>
  );
}

// ── Tier summary card ─────────────────────────────────────────────────────────

function TierSummaryCard({ tierKey, tierCfg }: { tierKey: TierKey; tierCfg: TierConfig }) {
  const COLORS: Record<TierKey, string> = { guest: "#5b5a66", loggedIn: "#2563eb", pro: "#7c3aed" };
  const LABELS: Record<TierKey, string> = { guest: "Guest", loggedIn: "Logged-in", pro: "Pro" };

  return (
    <div className={styles.tierCard}>
      <div className={styles.tierCardHead}>
        <span className={styles.tierBadge} style={{ background: COLORS[tierKey] }}>{LABELS[tierKey]}</span>
      </div>
      <div className={styles.tierCardRows}>
        <div className={styles.tierCardRow}>
          <span>Model</span>
          <strong>{tierCfg.model?.name ?? <em>not set</em>}</strong>
        </div>
        <div className={styles.tierCardRow}>
          <span>Rate limit</span>
          <strong>{tierCfg.rateLimitPolicy?.name ?? <em>none</em>}</strong>
        </div>
        <div className={styles.tierCardRow}>
          <span>Guardrails</span>
          <strong>{tierCfg.guardrails.length > 0 ? tierCfg.guardrails.map((g) => g.name).join(", ") : <em>none</em>}</strong>
        </div>
        <div className={styles.tierCardRow}>
          <span>MCP tools</span>
          <strong>{tierCfg.mcpTools.length > 0 ? tierCfg.mcpTools.map((t) => t.name).join(", ") : <em>none</em>}</strong>
        </div>
      </div>
    </div>
  );
}

// ── AI Prompt panel ───────────────────────────────────────────────────────────

function AiPromptPanel({
  claudePrompt,
  codexPrompt,
}: {
  claudePrompt: string;
  codexPrompt: string;
}) {
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  function copyAs(key: string, text: string) {
    navigator.clipboard.writeText(text).then(() => {
      setCopiedKey(key);
      setTimeout(() => setCopiedKey(null), 2200);
    });
  }

  return (
    <div className={styles.aiPanel}>
      <div className={styles.aiPanelLeft}>
        <p className={styles.aiPanelKicker}>One-click implementation</p>
        <h2 className={styles.aiPanelTitle}>Copy prompt for your AI coding assistant</h2>
        <p className={styles.aiPanelDesc}>
          Paste into Claude, ChatGPT, Cursor, Windsurf, or GitHub Copilot Chat.
          The prompt includes all widget code, your backend proxy, env vars, and step-by-step instructions.
        </p>
      </div>
      <div className={styles.aiPanelBtns}>
        <button
          className={`${styles.aiBtn} ${styles.aiBtnClaude} ${copiedKey === "claude" ? styles.aiBtnDone : ""}`}
          onClick={() => copyAs("claude", claudePrompt)}
        >
          <span className={styles.aiBtnIcon}>
            {/* Anthropic logo mark */}
            <svg width="22" height="15" viewBox="0 0 46 32" fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
              <path d="M32.73 0h-6.945L38.45 32h6.945zM13.55 0 0 32h7.078l2.78-7.216h14.33L26.93 32h7.032L20.494 0zm-1.51 19.072 4.53-11.77 4.531 11.77z"/>
            </svg>
          </span>
          <span className={styles.aiBtnLabel}>
            {copiedKey === "claude" ? "Copied!" : "Copy for Claude"}
          </span>
          <span className={styles.aiBtnSub}>Claude.ai · Claude Code · Cursor</span>
        </button>

        <button
          className={`${styles.aiBtn} ${styles.aiBtnCodex} ${copiedKey === "codex" ? styles.aiBtnDone : ""}`}
          onClick={() => copyAs("codex", codexPrompt)}
        >
          <span className={styles.aiBtnIcon}>
            {/* OpenAI logo mark */}
            <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
              <path d="M22.282 9.821a5.985 5.985 0 0 0-.516-4.91 6.046 6.046 0 0 0-6.51-2.9A6.065 6.065 0 0 0 4.981 4.18a5.985 5.985 0 0 0-3.998 2.9 6.046 6.046 0 0 0 .743 7.097 5.98 5.98 0 0 0 .511 4.91 6.051 6.051 0 0 0 6.515 2.9A5.985 5.985 0 0 0 13.26 23a6.056 6.056 0 0 0 5.772-4.206 5.99 5.99 0 0 0 3.997-2.9 6.056 6.056 0 0 0-.747-7.073zM13.26 21.95a4.475 4.475 0 0 1-2.876-1.04l.141-.081 4.779-2.758a.795.795 0 0 0 .392-.681v-6.737l2.02 1.168a.071.071 0 0 1 .038.052v5.583a4.504 4.504 0 0 1-4.494 4.494zM3.6 17.9a4.47 4.47 0 0 1-.535-3.014l.142.085 4.783 2.759a.771.771 0 0 0 .78 0l5.843-3.369v2.332a.08.08 0 0 1-.033.062L9.74 19.95A4.5 4.5 0 0 1 3.6 17.9zm-.83-9.063A4.485 4.485 0 0 1 5.14 6.87v4.07a.77.77 0 0 0 .388.676l5.815 3.355-2.02 1.168a.076.076 0 0 1-.071 0L4.95 13.28A4.504 4.504 0 0 1 2.77 8.837zm16.597 3.856-5.815-3.355 2.014-1.163a.076.076 0 0 1 .072 0l4.83 2.791a4.494 4.494 0 0 1-.676 8.104v-5.678a.79.79 0 0 0-.425-.699zm2.01-3.023-.141-.085-4.774-2.782a.776.776 0 0 0-.785 0L9.84 10.13V7.798a.066.066 0 0 1 .027-.062l4.83-2.786a4.5 4.5 0 0 1 6.68 4.662zM8.307 12.863l-2.02-1.164a.08.08 0 0 1-.038-.057V6.071a4.5 4.5 0 0 1 7.375-3.453l-.142.08L8.704 5.46a.795.795 0 0 0-.393.681zm1.098-2.365 2.602-1.5 2.607 1.5v2.999l-2.597 1.5-2.607-1.5z"/>
            </svg>
          </span>
          <span className={styles.aiBtnLabel}>
            {copiedKey === "codex" ? "Copied!" : "Copy for ChatGPT"}
          </span>
          <span className={styles.aiBtnSub}>ChatGPT · Copilot Chat · Windsurf</span>
        </button>
      </div>
    </div>
  );
}

// ── Publish page ──────────────────────────────────────────────────────────────

export function PublishPage() {
  const widgetConfigSnapshot = useSyncExternalStore(
    subscribeToSessionStorage,
    getWidgetConfigSnapshot,
    emptyStorageSnapshot,
  );
  const tierConfigSnapshot = useSyncExternalStore(
    subscribeToSessionStorage,
    getTierConfigSnapshot,
    emptyStorageSnapshot,
  );

  const cfg = readConfig(widgetConfigSnapshot);
  const tierCfg = readTierConfig(tierConfigSnapshot);

  const hasTiers = tierCfg !== null;

  const widgetCode   = buildWidgetComponent(cfg, tierCfg);
  const apiRouteCode = buildApiRoute(cfg, tierCfg);
  const usageCode    = buildUsageSnippet(hasTiers);
  const envCode      = buildEnvSnippet(tierCfg);

  const claudePrompt = buildClaudePrompt(cfg, tierCfg, widgetCode, apiRouteCode, usageCode, envCode);
  const codexPrompt  = buildCodexPrompt(cfg, tierCfg, widgetCode, apiRouteCode, usageCode, envCode);

  return (
    <div className={stepStyles.designer}>
      {/* ── Step header ── */}
      <section className={stepStyles.header}>
        <div className={stepStyles.stepRail} aria-label="Builder progress">
          <div className={stepStyles.stepNode}><span>1</span><strong>Widget UI</strong></div>
          <i />
          <div className={stepStyles.stepNode}><span>2</span><strong>Gateway</strong></div>
          <i />
          <div className={stepStyles.stepNode}><span>3</span><strong>Live test</strong></div>
          <i />
          <div className={`${stepStyles.stepNode} ${stepStyles.stepActive}`}><span>4</span><strong>Publish</strong></div>
        </div>
        <div>
          <h1>Ship your chatbot</h1>
          <p>
            {hasTiers
              ? "Your tier config, widget design, and gateway are ready. Copy the code and drop it into your project."
              : "Your widget design is ready. Copy the component and add a backend proxy to go live."}
          </p>
        </div>
        <div className={stepStyles.headerActions}>
          <Link className={stepStyles.secondaryButton} href="/builder/step-three">Back</Link>
        </div>
      </section>

      {/* ── AI Prompt panel ── */}
      <AiPromptPanel claudePrompt={claudePrompt} codexPrompt={codexPrompt} />

      {/* ── Main content ── */}
      <div className={styles.publishBody}>

        {/* Tier summary */}
        {hasTiers && tierCfg ? (
          <div className={styles.section}>
            <div className={styles.sectionHead}>
              <div className={styles.sectionNumCheck}>✓</div>
              <div>
                <h2>Your gateway configuration</h2>
                <p>Auto-imported from your TrueFoundry tenant. Already baked into the code below.</p>
              </div>
            </div>
            <div className={styles.tierGrid}>
              {(["guest", "loggedIn", "pro"] as TierKey[]).map((k) => (
                <TierSummaryCard key={k} tierKey={k} tierCfg={tierCfg.tiers[k]} />
              ))}
            </div>
            {tierCfg.gatewayUrl && (
              <div className={styles.gwUrlRow}>
                <span>Gateway</span>
                <code>{tierCfg.gatewayUrl}</code>
              </div>
            )}
          </div>
        ) : null}

        {/* Step 1: Install */}
        <div className={styles.section}>
          <div className={styles.sectionHead}>
            <div className={styles.sectionNum}>1</div>
            <div>
              <h2>Install the OpenAI SDK</h2>
              <p>The backend proxy uses the OpenAI-compatible client to call your TrueFoundry gateway.</p>
            </div>
          </div>
          <div className={styles.codeBlock}>
            <div className={styles.codeRow}>
              <span className={styles.codePrompt}>$</span>
              <code>npm install openai</code>
            </div>
            <div className={styles.codeRow}>
              <span className={styles.codePrompt}>$</span>
              <code>pnpm add openai</code>
            </div>
            <CopyButton text="npm install openai" />
          </div>
        </div>

        {/* Step 2: Widget component */}
        <div className={styles.section}>
          <div className={styles.sectionHead}>
            <div className={styles.sectionNum}>2</div>
            <div>
              <h2>ChatDockWidget.tsx</h2>
              <p>
                Self-contained React component — all styles are injected at runtime via a{" "}
                <code>&lt;style&gt;</code> tag. No CSS files, no extra packages.
                Drop it into <code>components/ChatDockWidget.tsx</code>.
              </p>
            </div>
          </div>
          <div className={styles.codeBlock}>
            <div className={styles.codeScrollable}>
              <pre><code>{widgetCode}</code></pre>
            </div>
            <CopyButton text={widgetCode} label="Copy ChatDockWidget.tsx" />
          </div>
        </div>

        {/* Step 3: Backend proxy */}
        <div className={styles.section}>
          <div className={styles.sectionHead}>
            <div className={styles.sectionNum}>3</div>
            <div>
              <h2>app/api/chat/route.ts</h2>
              <p>
                Server-side proxy — your TrueFoundry API key never reaches the browser.
                Streams SSE deltas back to the widget. Uses the OpenAI-compatible client.
              </p>
            </div>
          </div>
          <div className={styles.codeBlock}>
            <div className={styles.codeScrollable}>
              <pre><code>{apiRouteCode}</code></pre>
            </div>
            <CopyButton text={apiRouteCode} label="Copy route.ts" />
          </div>
        </div>

        {/* Step 4: Add to layout */}
        <div className={styles.section}>
          <div className={styles.sectionHead}>
            <div className={styles.sectionNum}>4</div>
            <div>
              <h2>Add to your layout</h2>
              <p>
                Import <code>ChatDockWidget</code> and render it inside <code>&lt;body&gt;</code>.
                {hasTiers ? " Pass the resolved user tier so the right model is selected." : ""}
              </p>
            </div>
          </div>
          <div className={styles.codeBlock}>
            <div className={styles.codeScrollable}>
              <pre><code>{usageCode}</code></pre>
            </div>
            <CopyButton text={usageCode} label="Copy usage" />
          </div>
        </div>

        {/* Step 5: Env vars */}
        <div className={styles.section}>
          <div className={styles.sectionHead}>
            <div className={styles.sectionNum}>5</div>
            <div>
              <h2>Environment variables</h2>
              <p>Add your TrueFoundry API key to <code>.env.local</code> — never commit this file.</p>
            </div>
          </div>
          <div className={styles.codeBlock}>
            <div className={styles.codeScrollable}>
              <pre><code>{envCode}</code></pre>
            </div>
            <CopyButton text={envCode} label="Copy .env snippet" />
          </div>
        </div>

        {/* What's included */}
        <div className={styles.section}>
          <div className={styles.sectionHead}>
            <div className={styles.sectionNum}>6</div>
            <div>
              <h2>What&apos;s included in the widget</h2>
              <p>Everything that ran in the live test — exact same behaviour in your production app.</p>
            </div>
          </div>
          <div className={styles.featureTable}>
            {[
              ["Animations", `${cfg.animation} — spring cubic-bezier(0.34,1.56,0.64,1), 240ms`],
              ["Streaming", "SSE delta events, token-by-token rendering"],
              ["Typing indicator", "3-dot bounce animation while waiting for response"],
              ["Tier routing", hasTiers ? "Guest → Logged-in → Pro model selection" : "Single model, add userTier prop later"],
              ["Self-contained CSS", "Injected via <style> tag on mount — no CSS files"],
              ["Abort on unmount", "Cleans up in-flight requests when component unmounts"],
              ["Scroll to bottom", "Auto-scrolls as new tokens arrive"],
              ["Enter to send", "Shift+Enter for newline, Enter to submit"],
            ].map(([feature, detail]) => (
              <div key={feature} className={styles.featureRow}>
                <code>{feature}</code>
                <span>{detail}</span>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
}
